---
- debug: msg="website = {{website}}"
- debug: msg="template = {{template}}"
- debug: msg="add_www = {{add_www}}"
- debug: msg="disable_default_site = {{disable_default_site}}"
- debug: msg="letsencrypt_tls = {{letsencrypt_tls}}"


- name: Copy virtual-host config file for {{website}}
  template: src={{template}}.j2 dest=/etc/apache2/sites-available/{{website}}.conf
  become: true

- name: Enable virtual host - {{ website }}
  command: a2ensite {{ website }}.conf
  notify:
    - Restart apache2
  become: true

- name: Disable default site
  shell: a2dissite 000-default.conf
  become: true
  when: disable_default_site
  notify:
    - Restart apache2

- name: Disable default site
  shell: a2dissite default-ssl.conf
  become: true
  when: disable_default_site
  notify:
    - Restart apache2

- name: Add PPA for letsencrypt
  action: apt_repository repo=ppa:certbot/certbot
  become: true
  when: letsencrypt_tls

- name: Update APT cache after adding PPA
  action: apt update_cache=yes
  become: true
  when: letsencrypt_tls

- name: Install letsencrypt
  action: apt pkg=python-certbot-apache state=installed
  become: true
  when: letsencrypt_tls

- name: Install letsencrypt TLS
  command: certbot --apache --agree-tos --email {{certbot_tos_email}} --domain {{website}} --redirect --quiet
  become: true
  when: letsencrypt_tls
  notify:
    - Restart apache2
